/* eslint-disable prettier/prettier */
export const turf = [
  {
    id: 1,
    name: 'Red turf',
    mobile: '1234567890',
    opening_time: '10:00 AM',
    closing_time: '10:00 PM',
    location: 'New York',
    turf_type: 'Indoor',
    turf_price: 1000,
  },
  {
    id: 2,
    name: 'Green Field',
    mobile: '9876543210',
    opening_time: '8:00 AM',
    closing_time: '8:00 PM',
    location: 'Los Angeles',
    turf_type: 'Outdoor',
    turf_price: 1200,
  },
  {
    id: 3,
    name: 'Sunny Turf',
    mobile: '4567891230',
    opening_time: '9:00 AM',
    closing_time: '9:00 PM',
    location: 'Chicago',
    turf_type: 'Indoor',
    turf_price: 1100,
  },
  {
    id: 4,
    name: 'Elite Turf',
    mobile: '3216549870',
    opening_time: '7:00 AM',
    closing_time: '7:00 PM',
    location: 'Houston',
    turf_type: 'Outdoor',
    turf_price: 1300,
  },
  {
    id: 5,
    name: 'Prime Turf',
    mobile: '7891234560',
    opening_time: '6:00 AM',
    closing_time: '6:00 PM',
    location: 'San Francisco',
    turf_type: 'Indoor',
    turf_price: 1500,
  },
];
