/* eslint-disable prettier/prettier */
export const turf = [
  {
    id: '1',
    name: 'Red turf',
    mobile: '1234567890',
    opening_time: '10:00 AM',
    closing_time: '10:00 PM',
    location: 'New York',
    turf_types: ['Indoor'],
    email: 'a@gmail.com',
    password: '1000',
  },
  {
    id: '2',
    name: 'Green Field',
    mobile: '9876543210',
    opening_time: '8:00 AM',
    closing_time: '8:00 PM',
    location: 'Los Angeles',
    turf_types: ['Outdoor'],
    email: 'g@gmail.com',
    password: '2000',
  },
  {
    id: '3',
    name: 'Sunny Turf',
    mobile: '4567891230',
    opening_time: '9:00 AM',
    closing_time: '9:00 PM',
    location: 'Chicago',
    turf_types: ['Indoor'],
    email: 's@gmail.com',
    password: '3000',
  },
  {
    id: '4',
    name: 'Elite Turf',
    mobile: '3216549870',
    opening_time: '7:00 AM',
    closing_time: '7:00 PM',
    location: 'Houston',
    turf_types: ['Outdoor'],
    email: 'e@gmail.com',
    password: '4000',
  },
  {
    id: '5',
    name: 'Prime Turf',
    mobile: '7891234560',
    opening_time: '6:00 AM',
    closing_time: '6:00 PM',
    location: 'San Francisco',
    turf_types: ['Indoor'],
    email: 'p@gmail.com',
    password: '5000',
  },
];
